// <auto-generated />
using System;
using CareFinder.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CareFinder.API.Migrations
{
    [DbContext(typeof(CareFinderDbContext))]
    [Migration("20240312135640_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CareFinder.API.Data.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HospitalId")
                        .HasColumnType("int");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HospitalId");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressLine = "20A Thompson Ave, Ikoyi",
                            HospitalId = 1,
                            PostalCode = "106104",
                            State = "Lagos"
                        },
                        new
                        {
                            Id = 2,
                            AddressLine = "3/5 Adetola Ayeni St, off Freedom Way, Lekki Phase I",
                            HospitalId = 2,
                            PostalCode = "105102",
                            State = "Lagos"
                        },
                        new
                        {
                            Id = 3,
                            AddressLine = "39 Isaac John str, GRA,Ikeja",
                            HospitalId = 3,
                            PostalCode = "106104",
                            State = "Lagos"
                        },
                        new
                        {
                            Id = 4,
                            AddressLine = "Ishaga Rd,Idi-Araba",
                            HospitalId = 4,
                            PostalCode = "102215",
                            State = "Lagos"
                        },
                        new
                        {
                            Id = 5,
                            AddressLine = "57 Campbell St, Lagos Island",
                            HospitalId = 5,
                            PostalCode = "101001",
                            State = "Lagos"
                        },
                        new
                        {
                            Id = 6,
                            AddressLine = "7 Ogalade Close off Ologun Agbaje Street, Victoria Island",
                            HospitalId = 6,
                            PostalCode = "101001",
                            State = "Lagos"
                        },
                        new
                        {
                            Id = 7,
                            AddressLine = "2A Keffi Street, By Toyan St",
                            HospitalId = 7,
                            PostalCode = "101233",
                            State = "Lagos"
                        },
                        new
                        {
                            Id = 8,
                            AddressLine = "17B Bourdillon Rd, Ikoyi",
                            HospitalId = 8,
                            PostalCode = "106104",
                            State = "Lagos"
                        },
                        new
                        {
                            Id = 9,
                            AddressLine = "22 Abioro St, Ikate, Lekki",
                            HospitalId = 9,
                            PostalCode = "106104",
                            State = "Lagos"
                        },
                        new
                        {
                            Id = 10,
                            AddressLine = "67 Oduduwa Cres, Ikeja GRA, Ikeja",
                            HospitalId = 10,
                            PostalCode = "101233",
                            State = "Lagos"
                        },
                        new
                        {
                            Id = 11,
                            AddressLine = "45 New Umuahia Rd, Umu Okahia, Aba",
                            HospitalId = 11,
                            PostalCode = "453106",
                            State = "Abia"
                        },
                        new
                        {
                            Id = 12,
                            AddressLine = "7 Ogalade Close off Ologun Agbaje Street, Victoria Island",
                            HospitalId = 12,
                            PostalCode = "101001",
                            State = "Lagos"
                        });
                });

            modelBuilder.Entity("CareFinder.API.Data.ApiUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("CareFinder.API.Data.Hospital", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("About")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ownership")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Hospitals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            About = "FCC Healthcare is a comprehensive cardiovascular and preventative health care hospital that empowers patients in Nigeria with their health care needs. For over 10 years, we have been delivering the highest quality comprehensive care in Nigeria by innovative use of modern technology and a commitment to local capacity building, education, and collaborative research. We put the patient first, and we have built a healthy medical environment to provide patients with comprehensive care, and deliver excellence in healthcare every day, and not just on some days.",
                            Email = "info@firstcardiology.org",
                            Name = "First Cardiology Consultants",
                            Ownership = "Private",
                            PhoneNumber = "08082114266",
                            Specialization = "Cardiology",
                            Website = "https://firstcardiology.org/"
                        },
                        new
                        {
                            Id = 2,
                            About = "LECC is a multidisciplinary cardiovascular and cardiac rehabilitation 24/7 facility focused on the treatment and management of cardiovascular diseases and trigger diseases using both invasive and non-invasive procedures, as well as preventive cardiology. Our skilled and experienced cardiologists, vascular and cardiothoraxic surgeons, electrophysiologists, interventional cardiologists and support staff are committed to the treatment and prevention of heart diseases through innovative, state-of-the-art technology. Our support staff include stroke specialists, sleep specialists, endocrinologists (diabetes), nutritionists, physiotherapists, pulmonologists and respiratory physicians.",
                            Email = "admin@thelecc.com",
                            Name = "Lagos Executive Cardiovascular Centre",
                            Ownership = "Private",
                            PhoneNumber = "08173651737",
                            Specialization = "Endocrinology",
                            Website = "https://thelecc.com/"
                        },
                        new
                        {
                            Id = 3,
                            About = "Reddington is a 5-star, one-stop facility providing comprehensive solutions to your healthcare needs. The facility was set up as a tertiary centre with multiple specialties, committed to deliver excellent service in the medical field, with all departments supported by the latest technology and state-of-the-art medical equipment.",
                            Email = "info@reddingtonhospital.com",
                            Name = "Reddington Hospital",
                            Ownership = "Private",
                            PhoneNumber = "09165359769",
                            Specialization = "General",
                            Website = "https://reddingtonhospital.com/"
                        },
                        new
                        {
                            Id = 4,
                            About = "The Lagos University Teaching Hospital today is a foremost tertiary hospital with a mandate to provide excellent services of international standard in patient care, training & research",
                            Email = "info@luth.gov.ng",
                            Name = "Lagos University Teaching Hospital (LUTH)",
                            Ownership = "Public",
                            PhoneNumber = "+2348128364824",
                            Specialization = "General",
                            Website = "https://luth.gov.ng/"
                        },
                        new
                        {
                            Id = 5,
                            About = "St. Nicholas Hospital is a private hospital located in Lagos Island in Lagos, Nigeria. It was founded in 1968 by Moses Majekodunmi. The hospital is in a building of the same name located at 57 Campbell Street near Catholic Mission Street. It has other facilities at different locations in Nigeria. Their other locations are: St. Nicholas Hospital, Maryland, St. Nicholas Clinics, Lekki Free Trade Zone, St. Nicholas Clinics, 7b Etim Inyang Street, Victoria Island.",
                            Email = "info@saintnicholashospital.com",
                            Name = "St. Nicholas Hospital",
                            Ownership = "Private",
                            PhoneNumber = "+2348035251295",
                            Specialization = "General",
                            Website = "https://saintnicholashospital.com/"
                        },
                        new
                        {
                            Id = 6,
                            About = "The Premier Specialists’ Medical Centre is the manifestation of a dream to promote the highest possible complete health care service, attainable in the most developed parts of the world, in Nigeria. Premier, as the name implies, means the first among all. We are a specialist hospital whose aim is to serve the healthcare needs of our community by providing quality and  comprehensive health care with the application of modern technology.",
                            Email = "info@thepremiermedical.com",
                            Name = "The Premier Specialists' Medical Centre",
                            Ownership = "Private",
                            PhoneNumber = "08143914895",
                            Specialization = "General",
                            Website = "https://thepremiermedical.com/"
                        },
                        new
                        {
                            Id = 7,
                            About = "We are a mother and child friendly, medical and surgical private hospital registered with both Corporate Affairs Commission and Lagos State Private Hospital Registration Authority. We have also been appointed as participating Health Care Service Provider in the National Health Insurance Scheme(CODE LA / 1204 / P) with over Eighteen(18) Health Maintenance Organisation(HMO) registered with us and Nigeria Maritime Administration and Safety Agency(NIMASA).",
                            Email = "info@bestcarehospitalng.com",
                            Name = "Best Care Hospital",
                            Ownership = "Private",
                            PhoneNumber = " 09013617520",
                            Specialization = "Gynecology",
                            Website = "https://www.bestcarehospitalng.com/"
                        },
                        new
                        {
                            Id = 8,
                            About = "Lagoon Hospital was founded in 1986 with its flagship situated at Apapa. Joint Commission International is the world’s leader in healthcare accreditation and the author and evaluator of the most rigorous international standards in quality and patient safety. For consecutive periods, Lagoon Hospitals has earned the Gold Seal of Approval from JCI by demonstrating continuous compliance with international best practices.The feat is a symbol of quality and reflects an organization’s commitment to providing safe and effective patient care. The JCI accreditation provides hospitals with the capacity to improve in various areas particularly with regards to staff education and development to core safety standards.",
                            Email = "livemorelife@lagoonhospitals.com",
                            Name = "Iwosan Lagoon Hospitals",
                            Ownership = "Private",
                            PhoneNumber = " +2347080609000",
                            Specialization = "General",
                            Website = "https://www.lagoonhospitals.com/"
                        },
                        new
                        {
                            Id = 9,
                            About = "Atlantic Memorial Hospital Etta - Atlantic Memorial Hospital Lekki Lagos was established with the goal of providing an international level of health care for all Nigerians. Etta - Atlantic Memorial Hospital was established by physicians with training in the US, they have teamed up with bright and dedicated Nigerian physicians and other allied health professionals to provide excellent care based on standards set by the World Health Organization(WHO).",
                            Email = "hello@ettaatlantic.com",
                            Name = "Etta Atlantic Memorial Hospital",
                            Ownership = "Private",
                            PhoneNumber = "+234(0)8083734008",
                            Specialization = "General",
                            Website = "https://www.ettaatlantic.com/"
                        },
                        new
                        {
                            Id = 10,
                            About = "Atlantic Memorial Hospital Etta - Atlantic Memorial Hospital Lekki Lagos was established with the goal of providing an international level of health care for all Nigerians. Etta - Atlantic Memorial Hospital was established by physicians with training in the US, they have teamed up with bright and dedicated Nigerian physicians and other allied health professionals to provide excellent care based on standards set by the World Health Organization(WHO).",
                            Email = "admin@genesishospitalng.com",
                            Name = "Genesis Specialist Hospital",
                            Ownership = "Private",
                            PhoneNumber = "+2348027340743",
                            Specialization = "General",
                            Website = "https://genesishospitalng.com/"
                        },
                        new
                        {
                            Id = 11,
                            About = "We are passionate about the healthcare we provide, which is centred around maternal and fetal wellbeing, Obstetric and gynaecological cases. Our aim is to provide our patients with the best possible healthcare service, also as we continually look to improve on our service delivery. Caring for the whole woman",
                            Email = "info@princessmaryspecialisthospital.com",
                            Name = "Princess Mary Specialist Hospital",
                            Ownership = "Private",
                            PhoneNumber = "08064063393",
                            Specialization = "Others",
                            Website = "https://www.google.com/maps/place/Princess+Mary+Specialist+Hospital/@5.1240079,7.3938909,17z/data=!3m1!4b1!4m6!3m5!1s0x1042991e2e740205:0x92fc9395cbb85871!8m2!3d5.1240079!4d7.3938909!16s%2Fg%2F11c2k36p3v?entry=ttu"
                        },
                        new
                        {
                            Id = 12,
                            About = "Living Word Mission Hospital (LWMH) is a mission established health care institution providing excellent services, quality patient â€“ friendly medical treatments to outright patients.",
                            Email = "info@livingwordweachinghospital.com",
                            Name = "Living Word Teaching Hospital",
                            Ownership = "Private",
                            PhoneNumber = "08062831218",
                            Specialization = "Others",
                            Website = "https://www.google.com/maps/place/Living+Word+Teaching+Hospital/@5.1376132,7.3499621,17z/data=!3m1!4b1!4m6!3m5!1s0x10429bd5db969fc1:0xe7ca643d4f43fec8!8m2!3d5.1376132!4d7.3499621!16s%2Fg%2F11c5dl6bzv?entry=ttu"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "13de9ccc-aede-438d-87bc-b3b206766565",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "0ad64030-e53d-46bd-9ee1-8859d9f55828",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CareFinder.API.Data.Address", b =>
                {
                    b.HasOne("CareFinder.API.Data.Hospital", "Hospital")
                        .WithMany("Addresses")
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hospital");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("CareFinder.API.Data.ApiUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("CareFinder.API.Data.ApiUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CareFinder.API.Data.ApiUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("CareFinder.API.Data.ApiUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CareFinder.API.Data.Hospital", b =>
                {
                    b.Navigation("Addresses");
                });
#pragma warning restore 612, 618
        }
    }
}
