// <auto-generated />
using CareFinder.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CareFinder.API.Migrations
{
    [DbContext(typeof(CareFinderDbContext))]
    [Migration("20240219152626_SeededHospitalsAndAddress")]
    partial class SeededHospitalsAndAddress
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CareFinder.API.Data.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine")
                        .HasColumnType("text");

                    b.Property<int>("HospitalId")
                        .HasColumnType("integer");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HospitalId");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressLine = "22, saliu street",
                            HospitalId = 3,
                            PostalCode = "1111",
                            State = "Lagos"
                        },
                        new
                        {
                            Id = 2,
                            AddressLine = "24, saliu street",
                            HospitalId = 1,
                            PostalCode = "1121",
                            State = "Ogun"
                        },
                        new
                        {
                            Id = 3,
                            AddressLine = "26, saliu street",
                            HospitalId = 2,
                            PostalCode = "1111",
                            State = "Lagos"
                        });
                });

            modelBuilder.Entity("CareFinder.API.Data.Hospital", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("About")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Ownership")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("Specialization")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Hospitals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            About = "asw dd ee eee fff vvv",
                            Email = "aaa@kk.com",
                            Image = "ffff",
                            Name = "Unilorin Teaching Hospital",
                            PhoneNumber = "12345",
                            Specialization = "General"
                        },
                        new
                        {
                            Id = 2,
                            About = "asw dd ee eee fff vvv",
                            Email = "aaa@kk.com",
                            Image = "sssssss",
                            Name = "UniLag Teaching Hospital",
                            PhoneNumber = "12345",
                            Specialization = "General"
                        },
                        new
                        {
                            Id = 3,
                            About = "asw dd ee eee fff vvv",
                            Email = "aaa@kk.com",
                            Image = "sssssss",
                            Name = "UniAbuja Teaching Hospital",
                            PhoneNumber = "12345",
                            Specialization = "General"
                        });
                });

            modelBuilder.Entity("CareFinder.API.Data.Address", b =>
                {
                    b.HasOne("CareFinder.API.Data.Hospital", "Hospital")
                        .WithMany("Addresses")
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hospital");
                });

            modelBuilder.Entity("CareFinder.API.Data.Hospital", b =>
                {
                    b.Navigation("Addresses");
                });
#pragma warning restore 612, 618
        }
    }
}
